package loki

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

// Names Loki accepts but the provider used to refuse: leading digit, spaces,
// colons. The old ^[a-zA-Z][a-zA-Z0-9-_.]*$ regex rejected all of these, which
// meant a rule file generated by the Grafana mixins could not be managed at
// all. Applying, reading back and destroying them exercises the escaping in the
// request paths and in the resource ID.
func TestAccResourceRuleGroupAlerting_unconventionalNames(t *testing.T) {
	// Init client
	client, err := NewAPIClient(setupClient())
	if err != nil {
		t.Fatal(err)
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckLokiRuleGroupDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccResourceRuleGroupAlerting_unconventionalNames,
				Check: resource.ComposeTestCheckFunc(
					testAccCheckLokiRuleGroupExists(
						"loki_rule_group_alerting.unconventional", "5xx errors", client),
					resource.TestCheckResourceAttr(
						"loki_rule_group_alerting.unconventional", "name", "5xx errors"),
					resource.TestCheckResourceAttr(
						"loki_rule_group_alerting.unconventional", "namespace", "ns with space"),
					resource.TestCheckResourceAttr(
						"loki_rule_group_alerting.unconventional", "rule.0.alert", "High 5xx rate"),
				),
			},
			{
				ResourceName:      "loki_rule_group_alerting.unconventional",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

const testAccResourceRuleGroupAlerting_unconventionalNames = `
resource "loki_rule_group_alerting" "unconventional" {
  name      = "5xx errors"
  namespace = "ns with space"

  rule {
    alert = "High 5xx rate"
    expr  = "{app=\"foo\"} |= \"error\""
    for   = "5m"

    labels = {
      severity = "warning"
    }

    annotations = {
      summary = "High 5xx rate"
    }
  }
}
`
